# This docker-compose deploys a jfrog artifactory
version: '3'

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    restart: always
    # TODO: CHANGE ME: After directory creation execute:
    # sudo chown -R 1030:1030 artifactory
    volumes:
      - ./artifactory:/var/opt/jfrog/artifactory
    environment:
      VIRTUAL_HOST: '${DOMAIN}'
      LETSENCRYPT_HOST: '${DOMAIN}'
      VIRTUAL_PORT: 8082
    expose:
      - 8081
      - 8082

  proxy:
    image: alpine/socat
    restart: always
    expose:
      - 80
    environment:
      VIRTUAL_HOST: 'api.${DOMAIN}'
      LETSENCRYPT_HOST: 'api.${DOMAIN}'
    command: ['tcp-listen:80,fork,reuseaddr', 'tcp-connect:artifactory:8081']

networks:
  default:
    name: nginx-proxy
    external: true
