# This docker-compose deploys two jfrog artifactories - one normal and one for apis
version: '3'

services:
  # Artifactory service itself
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    user: artifactory
    # The local directory needs to be owned by user 1030(artifactory)
    # -> After directory creation execute: sudo chown -R 1030:1030 artifactory/
    volumes:
      - ./artifactory:/var/opt/jfrog/artifactory
    working_dir: /opt/jfrog/artifactory
    restart: always
    expose:
      - 8081
      - 8082

  # Proxies
  artifactory-api-proxy:
    image: alpine/socat
    container_name: artifactory-api-proxy
    restart: always
    expose:
      - 80
    env_file: .env
    environment:
      VIRTUAL_HOST: 'api.${DOMAIN}'
      LETSENCRYPT_HOST: 'api.${DOMAIN}'
    command: ["tcp-listen:80,fork,reuseaddr", "tcp-connect:artifactory:8081"]
  artifactory-ui-proxy:
    image: alpine/socat
    container_name: artifactory-ui-proxy
    restart: always
    expose:
      - 80
    env_file: .env
    environment:
      VIRTUAL_HOST: '${DOMAIN}'
      LETSENCRYPT_HOST: '${DOMAIN}'
    command: ["tcp-listen:80,fork,reuseaddr", "tcp-connect:artifactory:8082"]

networks:
  default:
    name: nginx-proxy
    external: true