# This docker-compose deploys a static site (such as angular/vue/react app or just plain html/css/js files).
# Unknown url routes are redirect to the index.html which is the expected behaviour for
# SPAs = single page applications such as a vue app.
version: '3'

services:
  app:
    image: nginx:stable-alpine
    restart: always
    environment:
      VIRTUAL_HOST: '${DOMAIN}'
      LETSENCRYPT_HOST: '${DOMAIN}'
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    name: nginx-proxy
    external: true
